//! Rust interface to Gitea's Web API, generated by progenitor.
//!
//! # Usage
//!
//! ```no_run
//! use gitea_api::{Auth, Gitea};
//! use url::Url;
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let api = Gitea::new(
//!     Auth::Token("your-api-token"),
//!     Url::parse("https://gitea.example.com")?,
//! )?;
//! let version = api.get_version().send().await?.into_inner();
//! println!("Gitea version: {}", version.version.unwrap_or_default());
//! # Ok(())
//! # }
//! ```

// Include the progenitor-generated client code.
include!(concat!(env!("OUT_DIR"), "/codegen.rs"));

/// Deserialize a Vec that may be `null` in JSON (some APIs send `null` for empty arrays).
pub fn null_as_default<'de, D, T>(deserializer: D) -> Result<Vec<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    use serde::Deserialize;
    let opt: Option<Vec<T>> = Option::deserialize(deserializer)?;
    Ok(opt.unwrap_or_default())
}

/// Errors from the Gitea API client.
#[derive(Debug, thiserror::Error)]
pub enum GiteaError {
    /// Error from the underlying HTTP/API client.
    #[error("API error: {0}")]
    Api(#[from] progenitor_client::Error<types::ApiError>),
    /// HTTP/reqwest error.
    #[error("HTTP error: {0}")]
    Http(#[from] reqwest::Error),
    /// URL must use http or https scheme.
    #[error("URL must use http:// or https:// scheme")]
    HttpRequired,
    /// Authentication key contains non-ASCII characters.
    #[error("authentication key contains non-ASCII characters")]
    KeyNotAscii,
}

/// Method of authentication.
pub enum Auth<'a> {
    /// API access token.
    Token(&'a str),
    /// No authentication.
    None,
}

impl Auth<'_> {
    fn to_headers(&self) -> Result<reqwest::header::HeaderMap, GiteaError> {
        let mut headers = reqwest::header::HeaderMap::new();
        match self {
            Auth::Token(token) => {
                let mut header: reqwest::header::HeaderValue = format!("token {token}")
                    .try_into()
                    .map_err(|_| GiteaError::KeyNotAscii)?;
                header.set_sensitive(true);
                headers.insert("Authorization", header);
            }
            Auth::None => (),
        }
        Ok(headers)
    }
}

/// Wrapper around the progenitor-generated [`Client`] that adds authentication.
pub struct Gitea {
    client: Client,
    reqwest_client: reqwest::Client,
    base_url: String,
}

impl Gitea {
    /// Create a new client connected to the specified Gitea instance.
    pub fn new(auth: Auth, url: url::Url) -> Result<Self, GiteaError> {
        if !matches!(url.scheme(), "http" | "https") {
            return Err(GiteaError::HttpRequired);
        }

        let auth_headers = auth.to_headers()?;

        let reqwest_client = reqwest::Client::builder()
            .user_agent("gitea-api-rs")
            .default_headers(auth_headers)
            .build()
            .expect("failed to build reqwest client");

        // The OAS3 spec declares servers: [{"url": "{base}/api/v1"}],
        // so the base URL for the progenitor client is {instance_url}/api/v1.
        let mut base_url = url.to_string();
        if !base_url.ends_with('/') {
            base_url.push('/');
        }
        base_url.push_str("api/v1");

        let client = Client::new_with_client(&base_url, reqwest_client.clone());
        Ok(Self {
            client,
            reqwest_client,
            base_url,
        })
    }

    /// Make a raw GET request to a Gitea API path (e.g., "repos/owner/repo/projects").
    /// Auth headers are included automatically. Returns error on non-success status.
    pub async fn raw_get(&self, path: &str) -> Result<String, GiteaError> {
        let url = format!("{}/{}", self.base_url, path.trim_start_matches('/'));
        let resp = self.reqwest_client.get(&url).send().await?;
        let resp = resp.error_for_status()?;
        Ok(resp.text().await?)
    }

    /// Make a raw request with method, path, and optional JSON body.
    pub async fn raw_request(
        &self,
        method: reqwest::Method,
        path: &str,
        body: Option<&serde_json::Value>,
    ) -> Result<reqwest::Response, GiteaError> {
        let url = format!("{}/{}", self.base_url, path.trim_start_matches('/'));
        let mut req = self.reqwest_client.request(method, &url);
        if let Some(body) = body {
            req = req.header("Content-Type", "application/json").json(body);
        }
        Ok(req.send().await?)
    }

    /// Make a fully customizable request. Used by `gt api` for arbitrary endpoints
    /// with custom headers, methods, and bodies.
    pub async fn request(
        &self,
        method: reqwest::Method,
        url: &str,
        headers: &[(String, String)],
        body: Option<&serde_json::Value>,
    ) -> Result<reqwest::Response, GiteaError> {
        let mut req = self.reqwest_client.request(method, url);
        req = req.header("Accept", "application/json");
        for (key, value) in headers {
            req = req.header(key.as_str(), value.as_str());
        }
        if let Some(body) = body {
            req = req.header("Content-Type", "application/json").json(body);
        }
        Ok(req.send().await?)
    }

    /// Build a full URL from an API path (prepends base_url).
    pub fn url_for(&self, path: &str) -> String {
        format!("{}/{}", self.base_url, path.trim_start_matches('/'))
    }

    /// Get the base URL (e.g., "https://gitea.example.com/api/v1").
    pub fn base_url(&self) -> &str {
        &self.base_url
    }
}

// Re-export reqwest types that callers need
pub use reqwest::Method;
pub use reqwest::Response;

impl std::ops::Deref for Gitea {
    type Target = Client;
    fn deref(&self) -> &Client {
        &self.client
    }
}
